services:
  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://portfolio-api-v936.onrender.com/api
    domains:
      - schonenberg.dev
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/$1
      - type: rewrite
        source: /*
        destination: /index.html